DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRODUCT_ID BIGINT,
    APPLICATION_PRIORITY BIGINT,
    APPLICABLE_PRICE DECIMAL(10, 2),
    CURRENCY_CODE  VARCHAR(3)
);
